- name: Ensure user exists
  ansible.builtin.user:
    name: "{{ target_user }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    create_home: yes

- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ target_user }}/.ssh"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: '0700'

- name: Add public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ target_user }}"
    state: present
    key: "{{ hostvars['localhost'].pub_key_content.content | b64decode }}"

- name: Allow passwordless sudo for the user
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ target_user }}"
    content: "{{ target_user }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: '0440'

- name: Disable password authentication for SSH
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
