- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name: [curl, gpg, build-essential, libreadline-dev, zlib1g-dev, libsqlite3-dev, libffi-dev, libgdbm-dev, libncurses5-dev, libyaml-dev]
    state: present

- name: Create source directory
  file:
    path: /usr/local/src
    state: directory

- name: Download OpenSSL
  get_url:
    url: "https://www.openssl.org/source/openssl-{{ openssl_version }}.tar.gz"
    dest: "/usr/local/src/openssl-{{ openssl_version }}.tar.gz"

- name: Extract OpenSSL
  unarchive:
    src: "/usr/local/src/openssl-{{ openssl_version }}.tar.gz"
    dest: /usr/local/src
    remote_src: yes

- name: Build and install OpenSSL
  shell: |
    cd /usr/local/src/openssl-{{ openssl_version }}
    ./config --prefix={{ openssl_prefix }} --openssldir={{ openssl_prefix }} shared zlib
    make -j"$(nproc)"
    make install
  args:
    creates: "{{ openssl_prefix }}/bin/openssl"

- name: Import GPG keys
  become_user: "{{ rpx_user }}"
  shell: |
    gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys \
    409B6B1796C275462A1703113804BB82D39DC0E3 \
    7D2BAF1CF37B13E2069D6956105BD0E739499BDB || true
    curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
  environment:
    GNUPGHOME: "/home/{{ rpx_user }}/.gnupg"

- name: Install RVM
  become_user: "{{ rpx_user }}"
  shell: \
    \curl -sSL https://get.rvm.io | bash -s stable
  args:
    executable: /bin/bash
    creates: "/home/{{ rpx_user }}/.rvm"

- name: Install Ruby and Bundler
  become_user: "{{ rpx_user }}"
  shell: |
    source /home/{{ rpx_user }}/.rvm/scripts/rvm
    rvm install {{ ruby_version }} --with-openssl-dir={{ openssl_prefix }} --default
    gem install bundler
  args:
    executable: /bin/bash

- name: Deploy with Capistrano
  shell: |
    sudo -u {{ rpx_user }} bash -c '
      source ~/.rvm/scripts/rvm
      cd {{ app_path }}
      cap qa deploy BRANCH={{ deploy_branch }} USERNAME={{ rpx_user }}
    '
  args:
    executable: /bin/bash